# Generated by Django 3.0.4 on 2020-07-11 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=9999)),
                ('Album', models.CharField(max_length=9999)),
                ('Artist', models.CharField(max_length=9999)),
                ('Year', models.CharField(max_length=10)),
                ('Song_File', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Playlist_Name', models.CharField(max_length=999)),
                ('Visibility', models.CharField(max_length=100)),
                ('Playlist_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Songs_In_Playlist', models.ManyToManyField(blank=True, to='Musica.Song')),
            ],
        ),
    ]
