# Generated by Django 3.0.7 on 2020-07-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0002_song_album_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='Public',
            field=models.BooleanField(default=False),
        ),
    ]
